### ISSUE TITLE
Empty base `Option` move assignment operator does not work

### ISSUE THREAD

**Issue by jjcamp** [ampron/functional#3]
https://github.com/ampron/functional/blob/a174489ead1094e61221a3f01bc8e47e88c09e4b/functional/include/fun/option/option_inner.h#L33

`if (_variant)` should be `if (_variant == Tag::SOME)` and should probably just do `T::operator=(other)`, since the assignment is done purely for potential side-effects.

**Comment by ampron** [comment]
We definitely need to fix that conditional.
I don't understand your second comment, "should probably just do T::operator=(other), since the assignment is done purely for potential side-effects". Can you please show me an example of how you are proposing it be written?
